### ISSUE TITLE
Brief Thank you and Make Public Feature Request

### ISSUE THREAD

**Issue by thatTinker** [Malith-Rukshan/Suno-API#1]
Wanted to thank you for your work on this; it is the only open source API for Suno I have found easy to get setup and working. I plan to use this to tide me over until they make an API eventually, hopefully. I could not find your donation/tip button on Kofi, feel free to provide something that we can use to compensate you for your efforts. 

I was wondering if it is possible (either as it is currently setup or in the future) to, through the API, control whether a song is public as well as retrieve its public link. I use the API for live generation and it would be convenient for people to be able to access the songs they generated live later via the link instead of only via the MP3 I download.

thank you, much appreciated, sorry for any oversight if this is already in place and I simply missed it (or if it is simply not possible to do other than on the Suno site itself)

**Comment by Malith-Rukshan** [comment]
Hello,

Thank you for your encouraging words! I’m glad the Suno API has been useful to you. Regarding your feature request, it’s not currently available, but I’m open to implementing it in next version (`A new method to **return direct mp3 download link**`). Do you have any specific ideas or requirements for this feature?

For donations, you can support my work through [Ko-fi](https://ko-fi.com/malith).

Thanks for your support and suggestions!

**Comment by thatTinker** [comment]
> Hello,
> 
> Thank you for your encouraging words! I’m glad the Suno API has been useful to you. Regarding your feature request, it’s not currently available, but I’m open to implementing it in next version (A new method to **return direct mp3 download link**). Do you have any specific ideas or requirements for this feature?

- Set whether the song will be made public or not once it is generated
- If set to public, a link can be output to share it publically (currently we can make links to the audio stream and image by appending the song ID info to those URLs, but there is no way to change a song to public through the API or set it to make songs public by default). Since suno has their own URL structure for public links we can simply append onto that if it is possible to make the songs public once they are generated.

> 
> For donations, you can support my work through [Ko-fi](https://ko-fi.com/malith).

- This was noticed but it looks like donations to your KoFi have been disabled, we cannot find any button to actually tip.


Thanks!

**Comment by Malith-Rukshan** [comment]
Hello @thatTinker ,

Thank you for your suggestion! I've added a new `set_visibility()` method to the API that allow to set songs as public or private. This feature is **now available in the latest release**.

You can check out the release here: [v1.0.7](https://github.com/Malith-Rukshan/Suno-API/releases/tag/v1.0.7)
And here's the commit that introduced this update: [b865838...38302bcf](https://github.com/Malith-Rukshan/Suno-API/commit/b865838f4019f3638161010749a549f038302bcf)

Example Usage:
```python
from suno import Suno, ModelVersions

client = Suno(model_version=ModelVersions.CHIRP_V3_5)

# Generate Sample Song
clips = client.generate(
  prompt="A peaceful melody reflecting a serene landscape",
  is_custom=False,
  wait_audio=True
)

# Make All Private | Link Only
for song in clips:
  is_public = client.set_visibility(song_id=song.id, is_public=False)
  print(is_public)
```

Please feel free to test this new feature and let me know if everything works as expected or if there are any further improvements you would like to see.

Thank you for contributing to the improvement of Suno-API!
