### ISSUE TITLE
Failed to get session id,

### ISSUE THREAD

**Issue by abc8350712** [Malith-Rukshan/Suno-API#2]
Exception: Failed to get session id, you may need to update the SUNO_COOKIE

However the cookie is what i found.

**Comment by Malith-Rukshan** [comment]
Hello! It looks like you might be **missing a step in the setup process**. Please double-check the [Prerequisites](https://github.com/Malith-Rukshan/Suno-API?tab=readme-ov-file#-prerequisites) section of the [README](https://github.com/Malith-Rukshan/Suno-API/blob/main/README.md) to ensure you have your `SUNO_COOKIE` correctly configured.

**Comment by abc8350712** [comment]
> Hello! It looks like you might be **missing a step in the setup process**. Please double-check the [Prerequisites](https://github.com/Malith-Rukshan/Suno-API?tab=readme-ov-file#-prerequisites) section of the [README](https://github.com/Malith-Rukshan/Suno-API/blob/main/README.md) to ensure you have your `SUNO_COOKIE` correctly configured.

Thank you. My mistake. It works now.
