### ISSUE TITLE
I want to rename the files to use the song title rather than ID

### ISSUE THREAD

**Issue by mylegitches** [Malith-Rukshan/Suno-API#4]
In the console I can see the song IDs, but I am not advanced enough to go through your library to figure out how to 'grab' them.  

Basically, I am downloading the files into a directory, but they not really discernable via the song ID.  I want to rename them using the sing title once the download completes. I can do this if I have the song ID so i can find that filename and rename it later.

**Comment by Malith-Rukshan** [comment]
Hello @mylegitches,

I've updated the Suno-API with commit [c789c3359d....](https://github.com/Malith-Rukshan/Suno-API/commit/c789c3359d2cc6b70d09ac289c681050bd805ca9). The `download()` function now saves **songs with both the song name and ID.** This should help you identify and manage the files more easily.

Check out the latest commit and let me know if you have any questions!
